services:
  - docker

before_install:
  - docker build -t slootsantos/node-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run slootsantos/node-react-test npm test -- --coverage

after_success:
  - docker build -t slootsantos/node-micro-client ./client
  - docker build -t slootsantos/node-micro-server ./server
  - docker build -t slootsantos/node-micro-worker ./worker
  - docker build -t slootsantos/node-micro-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push slootsantos/node-micro-client
  - docker push slootsantos/node-micro-server
  - docker push slootsantos/node-micro-worker
  - docker push slootsantos/node-micro-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: node-docker-micro
  env: NodeDockerMicro-env
  bucket_name: elasticbeanstalk-eu-west-1-727205521166
  bucket_path: node-docker-micro
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
